---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2018/10/11 下午12:06
---



IS_IOS = System:iOS()
IS_ANDROID = System:Android()


----------------------------------------------------
----------------------------------------------------
--------------------- 宽高定义 ----------------------
----------------------------------------------------
----------------------------------------------------


kNavBarHeight = System:navBarHeight()
kStatusBarHeight = System:stateBarHeight()


-- widow的宽高和屏幕的宽高可能不同
-- 当资源在LuaView中使用时，建议使用window的宽高
-- 在controller中时建议使用screen宽高
kWindowWidth  = window:width()
kWindowHeight = window:height()
kScreenWidth  = System:screenSize():width()
kScreenHeight = System:screenSize():height()
kScreenScale  = (kScreenWidth / 375)

if IS_ANDROID then
    window:setStatusBarStyle(StatusBarStyle.Default)
    kScreenHeight = kWindowHeight + kStatusBarHeight
    kNavBarHeight = 44
    -- 安卓5.0以下不支持状态栏沉浸
    if System:OSVersionInt() < 21 then
        kStatusBarHeight = 0
    end
end

if IS_IOS then
    -- iOS为Toast提示时间
    kToastTime = 1.5
else
    -- 安卓为 0/1
    kToastTime = 1
end


---
--- 处理不确定是否存在的方法调用，并返回响应结果。
--- 第一个返回值指方法是否存在且被正确调用
--- 其后的返回值为函数不存在或执行异常信息，或函数正确执行后返回的结果
---
---@param obj   any 方法调用者
---@param funcName  string      方法名
---@param ...   any 可变参数
---
---@return boolean
---
luaCall = function(obj, funcName, ...)
    local mt = getmetatable(obj) or (type(obj) == "table" and obj or {})
    if mt and type(mt[funcName]) == "function" then
        return pcall(obj[funcName], obj, ...)
    end
    return false, "attempt to call a nil value or vm is LuaJ"
end

-- 通过指定__call可以使表接收一些参数，从而调用__call指向的方法
__weak = setmetatable({}, {__mode = "v", __call = function(_, v)
    local w = {}
    __weak[w] = v
    return w
end })