---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by song.meng
--- DateTime: 2019/8/9 下午5:30
---
--- 可取消的延时任务
---

local TaskOperation = require("util.BaseEntryFile"):extend()

function TaskOperation:init(task, timeInterval)
    timeInterval = timeInterval or 0.001

    if type(task) == "function" then
        self.task = task

        self.timer = Timer()
                :interval(timeInterval)
                :repeatCount(0)
                :start(task)
    end

    return self
end

-- 立即执行
function TaskOperation:startRecently()
    if type(self.task) == "function" then
        self.task()
        self.timer:stop()
        self.timer = nil
    end
end

-- 取消任务
function TaskOperation:cancel()
    self.timer:stop()
    self.timer = nil
end

return TaskOperation